version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8123:8123"
    volumes:
      # Mount local chroma_db for development
      - ./chroma_db:/app/chroma_db
      - ./credentials:/app/credentials
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8123/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  chroma_data:
    driver: local