version: '3.8'

services:
  wells-slack-bot:
    build:
      context: ..
      dockerfile: production/Dockerfile.slack
    ports:
      - "8000:8000"  # Slack Bot API
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.production
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 